Agrega descarga_datos
IslasGECI/docker pull request #4
Opened 2020-05-13 04:32 UTC by evaristor

El módulo `descarga_datos` lo usamos en muchos análisis. Aquí lo estoy agregando a nuestras imágenes _Base_ y _Jupyter_ por solicitud de @islasfernando.

Revisa que:

- [ ] [GitHub Actions](https://github.com/IslasGECI/docker/actions) está pasando
- [ ]  Ejecuta localmente: `make --makefile=Makefile.build dockerfiles`
- [ ] Construye la base: `docker build --tag islasgeci/base --file Dockerfile.base .`
- [ ] Construye Jupyter: `docker build --tag islasgeci/jupyter --file Dockerfile.jupyter .`
- [ ] Corre las pruebas de la base `docker run --volume ${PWD}:/workdir islasgeci/base make tests`
- [ ] Corre las pruebas de Jupyter `docker run --volume ${PWD}:/workdir islasgeci/jupyter make`
- [ ] Entra a un contenedor y verifica que `descarga_datos` está instalado

[Instala descarga_datos en imágenes Base y Jupyter](https://app.gitkraken.com/glo/board/5e711b4e31df0b001242edf6/card/5eb183cf4435d10014b82fda)

2020-05-18 20:55 UTC, islasfernando requested changes
Al correr localmente el 3er bullet `docker build --tag islasgeci/base --file Dockerfile.base .` obtuve:
```
...
Step 10/15 : RUN git clone https://github.com/IslasGECI/queries.git &&     cd queries &&     make install &&     make tests &&     cd .. &&     rm --recursive queries
 ---> Running in 689f9adbc121
Cloning into 'queries'...
mkdir --parents /usr/local/bin
cp ./src/* /usr/local/bin
chmod +x /usr/local/bin/*
export PATH="/usr/local/bin:${PATH}"
# Doctest:
mkdir --parents /usr/local/doctests
cp ./tests/test_*.py /usr/local/doctests
mkdir --parents /usr/local/bin
cp ./src/* /usr/local/bin
chmod +x /usr/local/bin/*
export PATH="/usr/local/bin:${PATH}"
# Doctest:
mkdir --parents /usr/local/doctests
cp ./tests/test_*.py /usr/local/doctests
shell-doctest test tests/test_cambia_formato_fecha.py | grep "failures" && exit 1 || exit 0
/bin/bash: shell-doctest: command not found
cambia_formato_fecha --help | grep "$ cambia_formato_fecha"
$ cambia_formato_fecha tests/data/test.csv
[ $(tail -1 tests/data/test.csv | cut --characters=1-11) == "01/Dic/2019" ] && \
    [ $(cambia_formato_fecha tests/data/test.csv | tail -1 | cut --characters=1-10) == "2019-12-01" ]
pip freeze | grep shelldoctest
/bin/bash: pip: command not found
make: *** [Makefile:9: test_dependencies] Error 1
The command '/bin/sh -c git clone https://github.com/IslasGECI/queries.git &&     cd queries &&     make install &&     make tests &&     cd .. &&     rm --recursive queries' returned a non-zero code: 2
```

2020-05-26 16:10 UTC, evaristor commented
Estoy en espera de que se acepte este _PR_: [queries #7](https://github.com/IslasGECI/queries/pull/7)

2020-05-26 19:10 UTC, evaristor commented
@islasfernando Por favor podrías checarlo nuevamente?

2020-05-29 20:59 UTC, islasfernando commented on _Dockerfile.header_base
> +FROM rocker/r-ubuntu:20.04
Contenedores ya en 20.04!

2020-05-29 20:59 UTC, islasfernando approved these changes

2020-05-29 21:00 UTC, devarops commented on _Dockerfile.header_base
> +FROM rocker/r-ubuntu:20.04
¡De una vez!

2020-05-29 21:03 UTC, merged

2020-06-08 16:11 UTC, MaritzaB reviewed
Se ve bien, solo unos errores de dedo en el README

2020-06-08 16:11 UTC, MaritzaB commented on README.md
> +Para trabajar en una terminal de Ubuntu ejecuata:
Creo que se te fue un error de dedo en _ejecuta_. ¿Podrías cambiarlo por favor?

2020-06-08 16:11 UTC, MaritzaB commented on README.md
> +Para trabajar en un _notebook_ de Jupyter ejecuata:
Igual aquí se te fué el error de dedo en _ejecuta_